### ISSUE TITLE
Search function on probelab.io website

### ISSUE THREAD

**Issue by yiannisbot** [plprobelab/website#67]
I thought that it would be useful to have a search function on the website, especially for those visitors that are not familiar with where to find what and don't want to read through everything. Starting this issue as something to consider in the (near?) future, as I don't have a clear view of how much effort it would be.

**Comment by dennis-tra** [comment]
There's a config option on the Hugo theme that enables a search field:

```toml
[params]
  # (Optional, default true) Enables search function with flexsearch,
  # Index is built on fly, therefore it might slowdown your website.
  # Configuration for indexing can be adjusted in i18n folder per language.
  BookSearch = true
```

From: https://github.com/alex-shpak/hugo-book#site-configuration
